name: ${project.artifactId}
main: com.kh498.main.Main
version: ${project.version}

description: Addon to Njol's Skript using Cybermaxke's MerchantsAPI to open merchant inventories within skript

depend: [Skript]
soft-depend: [Merchants]

authors: [kh498, Cybermaxke]